var mongoose = require('mongoose');

const preUserSchema = new mongoose.Schema({
  code: { type: String },
  name: { type: String, required: true },
  profileUrl: { type: String },
  phone: { type: String },
  username: { type: String },
  email: { type: String },
  year: { type: String },
  used: { type: Boolean, default: false },
  bio: { type: String },
  emailVerified: { type: Boolean, default: false },
  emailVerificationExpires: {type: String}
});

const PreUser = mongoose.model('PreUser', preUserSchema);

/*
const preUsersData = [
  {
    "name": "Aditi Khobragade",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Aditi Zade",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Akshita Ray",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Ashish Sopankar",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Bhavishya Rangari",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Himanshu Mangam",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Ketan Mongarkar",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Khushi Ramteke",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Manasvi Borkar",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Naina Khadsang",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Prajwal Chaudhari",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Prajwali Tajane",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Prajyot Meshram",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Prajyot Raut",
    "username": "",
    "profileUrl": "",
    "year": "2020-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Ritik Madavi",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Rutuja Kamdi",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Samiksha Chunarkar",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Samyak Sakhare",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Shankar Bharde",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Shraddha Pakhmode",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Sneha Togare",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Trupti Raut",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Ujwal Wadhai",
    "username": "",
    "profileUrl": "/images/ujwal_profile.jpg",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "wadhaiujwal@gmail.com",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Vivekanand Puram",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Aditya Patil",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Bhairavi Gedam",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Manali Humane",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Manthan Suryawanshi",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Monali Chandanbawane",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Paresh Nimje",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Pranjal Madkam",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Rhutik Kunbhare",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Sejal Ragit",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Shrishant Bagale",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Shrushti Khandare",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Suhani Chaudhary",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Vaishnavi Shedala",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Vedanti Fukat",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  },
  {
    "name": "Yash Magare",
    "username": "",
    "profileUrl": "",
    "year": "2017-24",
    "bio": "",
    "code": "",
    "phone": "",
    "email": "",
    "used": false,
    "emailVerified": false,
    "emailVerificationExpires": ""
  }
]


  try {
    const result = PreUser.insertMany(preUsersData);
    console.log(`Inserted ${result.length} pre-users.`);
    mongoose.connection.close();
  } catch (err) {
    console.error('Insert error:', err);
    mongoose.connection.close();
  }

*/

module.exports = PreUser;